name: QKDP
channels:
  - conda-forge
dependencies:
  - coverage
  - matplotlib
  - numba
  - numpy
  - pytest
  - ipykernel
  - jupyterlab
  - notebook
  - nox
  - codespell
  - line_profiler
  - rich
  - scipy
  - mplhep
  - scienceplots
